apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0
          args:
            - start-dev
            - --health-enabled=true
            - --https-client-auth=request
          startupProbe:
            httpGet:
              path: /health/ready
              port: auth
            initialDelaySeconds: 3
            failureThreshold: 30
            periodSeconds: 5
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: credential-sso
                  key: ADMIN_USERNAME
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credential-sso
                  key: ADMIN_PASSWORD
            - name: KC_PROXY
              value: edge
            - name: KC_DB
              value: "postgres"
            - name: "KC_DB_URL"
              value: "jdbc:postgresql://keycloak-db/keycloak"
            - name: "KC_DB_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: credential-sso
                  key: DB_USERNAME
            - name: "KC_DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: credential-sso
                  key: DB_PASSWORD
          ports:
            - name: auth
              containerPort: 8080
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/bash"
                  - "-c"
                  - "while ! /opt/keycloak/bin/kcadm.sh update realms/master -s sslRequired=NONE --server http://localhost:8080/ --realm master --user $KEYCLOAK_ADMIN --password $KEYCLOAK_ADMIN_PASSWORD --no-config; do sleep 10; done"


